# Generated by Django 2.1 on 2019-05-11 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190511_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('hostaccsess_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.hostaccessinfo')),
            ],
        ),
    ]
