# Generated by Django 2.1 on 2019-05-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_hostinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='sn',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='name',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
