# Generated by Django 2.1 on 2019-05-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20190512_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='inip',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='outip',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
