# Generated by Django 2.1 on 2019-05-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20190512_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='yewu',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
