# Generated by Django 2.1 on 2019-05-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_hostinfo_yewu'),
    ]

    operations = [
        migrations.CreateModel(
            name='iteminfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, unique=True)),
                ('iteminfo', models.CharField(blank=True, max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='weihuren',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='hostitem_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset.iteminfo'),
            preserve_default=False,
        ),
    ]
