# Generated by Django 2.1 on 2019-05-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20190512_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostaccessinfo',
            name='feiyong',
            field=models.IntegerField(default=100.1, max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
