# Generated by Django 2.1 on 2019-05-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_hostaccessinfo_feiyong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostaccessinfo',
            name='feiyong',
            field=models.FloatField(blank=True, max_length=64),
        ),
    ]
