# Generated by Django 2.1 on 2019-05-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20190512_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='cpu',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='neicun',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
