# Generated by Django 2.1 on 2019-05-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20190513_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='hostname',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
