# Generated by Django 2.1 on 2019-05-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_hostinfo_hostname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfo',
            name='yewu',
        ),
        migrations.AlterField(
            model_name='hostaccessinfo',
            name='feiyong',
            field=models.FloatField(blank=True, max_length=64, null=True),
        ),
    ]
