# Generated by Django 2.1 on 2019-05-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_auto_20190513_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostaccessinfo',
            name='accessinfo',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
