# Generated by Django 2.1 on 2019-05-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_auto_20190513_0502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='hostaccsess_name',
            new_name='hostaccsess_id',
        ),
        migrations.RenameField(
            model_name='hostinfo',
            old_name='hostitem_name',
            new_name='hostitem_id',
        ),
    ]
