# Generated by Django 2.1 on 2019-05-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_auto_20190513_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='shujuzhongxin',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
