# Generated by Django 2.1 on 2019-05-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_auto_20190514_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='xiangmu',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
