# Generated by Django 2.1 on 2019-05-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_auto_20190515_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='mem_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='num_cpus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='num_gpus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
